# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-11-14 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invest',
            name='trade_id',
        ),
    ]
